name: build-and-deploy

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  deploy-to-dev:
    name: Build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: "Deploy to dev"
        run: echo "Deploying to dev environment"

  deploy-to-prod:
    name: Build
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment: prod

    steps:
      - name: "Deploy to prod"
        run: echo "Deploying to prod environment"
